In [14]:
#Задание №1
import numpy as np

matrix_A = np.array([[1, 2, 1], [-2,1,1]])
matrix_B = np.array([[3, 1],[-1,0],[2,4]])
matrix_C = np.array([[-2, 2],[1,-1],[1,2]])

transpose_matrix_A = matrix_A.transpose()
result_1 = transpose_matrix_A + np.dot(matrix_B, 2)
print(result_1)
result_2 = matrix_B + np.dot(matrix_C, 2)
print(result_2)

[[7 0]
 [0 1]
 [5 9]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [15]:
#Задание №2
import numpy as np

matrix = np.zeros ((8,8))
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [16]:
#Задание №3
import numpy as np

vector1 = np.arange(0, 1.5, 0.1)
vector2 = np.arange(1, 7, 1)

matrix1 = vector1.reshape(5, 3)
matrix2 = vector2.reshape(3, 2)
matrix3 = np.dot(matrix1, matrix2)
print(matrix1)
print(matrix2)
print(matrix3)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [17]:
#Задание №4
import numpy as np

vector = np.arange(1, 73, 2, dtype=np.int32)
select = vector[vector % 3 == 0]
print(vector)
print(select)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
[ 3  9 15 21 27 33 39 45 51 57 63 69]
